#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-DBIx-Class-Schema-Config
Version  : 0.001014
Release  : 24
URL      : https://cpan.metacpan.org/authors/id/S/SY/SYMKAT/DBIx-Class-Schema-Config-0.001014.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/S/SY/SYMKAT/DBIx-Class-Schema-Config-0.001014.tar.gz
Summary  : 'Manage connection credentials for DBIx::Class::Schema'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-DBIx-Class-Schema-Config-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Config::Any)
BuildRequires : perl(DBD::SQLite)
BuildRequires : perl(DBIx::Class)
BuildRequires : perl(DBIx::Class::Schema)
BuildRequires : perl(File::HomeDir)
BuildRequires : perl(Hash::Merge)
BuildRequires : perl(URI)
BuildRequires : perl(namespace::clean)

%description
This archive contains the distribution DBIx-Class-Schema-Config,
version 0.001014:

%package dev
Summary: dev components for the perl-DBIx-Class-Schema-Config package.
Group: Development
Provides: perl-DBIx-Class-Schema-Config-devel = %{version}-%{release}
Requires: perl-DBIx-Class-Schema-Config = %{version}-%{release}

%description dev
dev components for the perl-DBIx-Class-Schema-Config package.


%package perl
Summary: perl components for the perl-DBIx-Class-Schema-Config package.
Group: Default
Requires: perl-DBIx-Class-Schema-Config = %{version}-%{release}

%description perl
perl components for the perl-DBIx-Class-Schema-Config package.


%prep
%setup -q -n DBIx-Class-Schema-Config-0.001014
cd %{_builddir}/DBIx-Class-Schema-Config-0.001014

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/DBIx::Class::Schema::Config.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
