#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-DBIx-Class-Schema-Config
Version  : 0.001011
Release  : 9
URL      : https://cpan.metacpan.org/authors/id/S/SY/SYMKAT/DBIx-Class-Schema-Config-0.001011.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/S/SY/SYMKAT/DBIx-Class-Schema-Config-0.001011.tar.gz
Summary  : 'Credential Management for DBIx::Class'
Group    : Development/Tools
License  : Artistic-1.0-Perl
BuildRequires : buildreq-cpan
BuildRequires : perl(Config::Any)
BuildRequires : perl(DBD::SQLite)
BuildRequires : perl(DBIx::Class)
BuildRequires : perl(File::HomeDir)
BuildRequires : perl(Hash::Merge)
BuildRequires : perl(Module::Install)
BuildRequires : perl(namespace::clean)

%description
No detailed description available

%package dev
Summary: dev components for the perl-DBIx-Class-Schema-Config package.
Group: Development
Provides: perl-DBIx-Class-Schema-Config-devel = %{version}-%{release}

%description dev
dev components for the perl-DBIx-Class-Schema-Config package.


%prep
%setup -q -n DBIx-Class-Schema-Config-0.001011

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.1/DBIx/Class/Schema/Config.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/DBIx::Class::Schema::Config.3
